### ISSUE TITLE
Resources in this stack

### ISSUE THREAD

**Issue by geohacker** [wri/project-zeno-deploy#1]
I think for a start this can be a standard cluster:
* [x] 1 node. I think we may separate LLM service into a different node later on
* [x] 1 postgresql database. I suppose RDS. Start with may `db.t4g.small` @leothomas is that too small?
* [x] Setup cluster level logging. @sunu what's our preferred approach now? Prometheus/graphana?

cc @yellowcap @srmsoumya

**Comment by leothomas** [comment]
Also noting that @srm had mentioned [langfuse](https://langfuse.com/) for logging the agent interactions/processes. There's a [langfuse-k8s framework](https://github.com/langfuse/langfuse-k8s) that we might make use of

**Comment by leothomas** [comment]
> Start with may db.t4g.small @leothomas is that too small?

Because PostgreSQL is backed by RDS the storage can essentially grow infinitely, so the instance size mainly affects the volume/speed of data ingestion and index building. The IVF Index build time grows with data volume, but doesn't occur in memory, so a small database will just take longer.  HNSW indexes, on the other hand, take orders of magnitude longer to build if the vectors cannot _all_ be held in memory. One way to get around this limitation is to bump the instance to a larger type (eg: `t4g.2xlarge`) during the insert and then bump back down afterwards.

Given that this is for a RAG pipeline (as opposed to something like an image similarity search) I don't think the index recall will be the biggest bottleneck in the output accuracy/quality, since text similarity is inherently "fuzzy" and we'll be collecting > 10 results per query. This means an IVF Index will very likely be more than enough

All this to say, `t4g.small` should be fine for now.
