### ISSUE TITLE
Separate dev and staging environments

### ISSUE THREAD

**Issue by yellowcap** [wri/project-zeno-deploy#3]
We will have the frontend team working across time zones using the zeno api. To be able to test new agents quickly, we need to be able to push changes without worrying that we block the frontend team. 

A simple dev & staging env separation is necessary to ensure that.

**Comment by sunu** [comment]
Fixed by https://github.com/wri/project-zeno-deploy/commit/009cc48181ea29d2c394ad493a64a359375e5397.

- The dev instance is available at: https://dev.api.zeno.ds.io/docs
- The staging instance is at: https://api.zeno.ds.io/docs

To deploy a new version:
- for dev, we need to update the image tag (which is the same as the full commit hash on the `main` branch of [project-zeno](https://github.com/wri/project-zeno)) at https://github.com/wri/project-zeno-deploy/blob/107038a7cb89611167868dd4fa0be53fa0445a33/helm/zeno/values-dev.yaml#L25
- for staging, similarly we need to update the image tag at https://github.com/wri/project-zeno-deploy/blob/107038a7cb89611167868dd4fa0be53fa0445a33/helm/zeno/values.yaml#L25
